name: Run NoAI Guardian

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  noai-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: NoAI Guardian
        uses: rahulraonatarajan/ai-guardian@v1.0.1
        with:
          path: '.'
          fix: 'false'  # Set to 'true' to auto-patch violations
